{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "envoy.serviceAccountName" . }}
  labels:
    helm.sh/chart: {{ template "envoy.chart" . }}
    app.kubernetes.io/name: {{ template "envoy.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
