{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.service.name }}{{ .Values.service.name }}{{ else }}{{ template "envoy.fullname" . }}{{ end }}
  labels:
    app: {{ template "envoy.name" . }}
    chart: {{ template "envoy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- with .Values.service.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    app: {{ template "envoy.name" . }}
    release: {{ .Release.Name }}
{{- end }}
